
server:
  port: 8200

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
        defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/
  server:

    use-read-only-response-cache: false
    enable-self-preservation: false
    peer-eureka-nodes-update-interval-ms: 6000
    eviction-interval-timer-in-ms: 6000